# Generated by Django 4.2.1 on 2023-05-30 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('traineeName', models.CharField(max_length=25)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courses')),
            ],
        ),
    ]
