# Generated by Django 4.2.1 on 2023-05-30 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_rename_courseid_trainees_coursename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainees',
            old_name='courseName',
            new_name='courseID',
        ),
    ]
