# Generated by Django 4.2.1 on 2023-05-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
